server:
  port: ${port}

spring:
  datasource:
    url: ${url}
    username: ${user}
    password: ${pwd}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  output:
    ansi:
      enabled: always
