server:
  port: ${SERVER_PORT:8080}
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always