app:
  allowed-urls: ${ALLOWED_URLS}
server:
  port: ${SERVER_PORT}

spring:
  config:
    import: file:env.properties
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      enabled: true
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      auto-index-creation: true
      database: ${MONGO_INITDB_ROOT_DATABASE}
