server:
  port: ${port}

spring:
  datasource:
    url: ${url}
    username: ${user}
    password: ${pwd}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  output:
    ansi:
      enabled: always
  mail:
    host: live.smtp.mailtrap.io
    port: 25
    username: api
    password: a66d1c56f094e6bd14c4c117712f8a45
    properties:
      mail:
        ssl: no
        smtp:
          auth: true
          tls: yes
          starttls:
            enable: true