app:
  upload-path: ${UPLOAD_PATH:/tmp/opensell-images}
  support-email: support@opensell.com
  allowed-urls: http://localhost:3000
spring:
  docker:
    compose:
      lifecycle-management: start-only
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: localhost
    port: 1025
    username: support@opensell.com
    password: NO_PASSWORD_IS_NEEDED_FOR_DEV
    default-encoding: UTF-8
  sql:
    init:
      mode: always