server:
  port: 8080
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      enabled: true
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      auto-index-creation: true
      database: opensell
