app:
  allowed-urls: ${ALLOWED_URLS}
server:
  port: ${SERVER_PORT}
spring:
  config:
    import: file:env.properties
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      
  output:
    ansi:
      enabled: always
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write-timeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
      verify:
        host: http://localhost:${port}


