app:
  server-url: ${SERVER_URL:http://localhost:8080}
  upload-path: ${UPLOAD_PATH:/tmp/opensell-images}
  support-email: ${SUPPORT_EMAIL:support@opensell.com}
  allowedUrls: ${ALLOWED_URLS:http://localhost:3000}
server:
  port: ${SERVER_PORT:8080}
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always