server:
  port: ${port}

spring:
  datasource:
    url: ${url}
    username: ${user}
    password: ${pwd}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: ${mailport}
    username: ${email}
    password: ${mailpassword}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write-timeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
      verify:
        host: http://localhost:${port}
